app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(48), unique=True, index=True)
    email = db.Column(db.String(48), unique=True, index=True)
    hash_pass = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError("You cannot read password attribute")

    @password.setter
    def password(self, password):
        self.hash_pass = generate_password_hash(password)

    def set_password(self, password):
        self.hash_pass = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.hash_pass, password)


class Blog(db.Model):
    __tablename__ = 'blogs'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    blog_content = db.Column(db.String())
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    blog_pic = db.Column(db.String(255))
    photo_url = db.Column(db.String(500))

    comment = db.relationship('Comment', backref='blog', lazy='dynamic')
    photo = db.relationship('Photo', backref='blog', lazy='dynamic')

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all_blogs(cls):
        blogs = Blog.query.order_by('-id').all()
        return blogs

    @classmethod
    def get_single_blog(cls, id):
        blog = Blog.query.filter_by(id=id).first()
        return blog


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    email = db.Column(db.String())
    comment_content = db.Column(db.String())
    date_comment = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blog_comments(cls, id):
        comments = Comment.query.filter_by(blog_id=id).order_by('-id').all()
        return comments

    @classmethod
    def get_single_comment(cls, id_blog, id):
        comment = Comment.query.filter_by(blog_id=id_blog, id=id).first()
        return comment


class Email(db.Model):
    __tablename__ = 'emails'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    email_data = db.Column(db.String(255))

    def save_email(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def send_single_email(cls, id):
        email = Email.query.filter_by(id=id).first()
        return email


class Photo(db.Model):
    __tablename__ = 'photos'
    id = db.Column(db.Integer, primary_key=True)
    photo_data = db.Column(db.String(255))
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required

class BlogForm(FlaskForm):
    title = StringField('Title', validators=[Required()],render_kw={"placeholder": "Title"})
    blog_data = TextAreaField('Type Blog here', validators=[Required()])
    photo_url = StringField('Photo URL', validators=[Required()], render_kw={'placeholder': 'Photo URL'})
    post = SubmitField('Post Blog')

class CommentForm(FlaskForm):
    name = StringField('Name',validators=[Required()],render_kw={"placeholder": "Name"})
    email = StringField('Email', validators=[Required()],render_kw={"placeholder": "Email"})
    comment_data = TextAreaField('Enter Comment', validators=[Required()],render_kw={"placeholder": "Comment"})
    post = SubmitField('Post Comment')
    

app/__init__.py
from flask import Flask 
from flask_bootstrap import Bootstrap
from config import config_options 
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_simplemde import SimpleMDE
from flask_mail import Mail

bootstrap = Bootstrap()  
db = SQLAlchemy()  
mail = Mail()
photos = UploadSet('photos', IMAGES)
simple = SimpleMDE()

login_manager = LoginManager()  
login_manager.session_protection = 'strong'  
login_manager.login_view = 'auth.login'  


def create_app(config_name):
    app = Flask(__name__) 

    # app configurations
    app.config.from_object(config_options[config_name])


    # initializing flask extensions
    bootstrap.init_app(app)  
    db.init_app(app)  
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # registering main app Blueprint
    from .main import main as main_blueprint  
    app.register_blueprint(main_blueprint)  

    # registering authentication blueprint
    from .auth import auth as auth_blueprint  # registering the Blueprint instance.
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')  

    # configure UploadSet
    configure_uploads(app, photos)  
    return app

app/main/__init__.py
from flask import Blueprint  
main = Blueprint('main', __name__)
from . import views, errors, forms

app/main/views.py
from flask import render_template, request, redirect, url_for, flash, abort
from . import main
from ..models import User, Blog, Comment
from flask_login import login_required, current_user
from .. import db, photos
from .forms import BlogForm, CommentForm
from datetime import datetime
import markdown2


@main.route('/', methods=['GET', 'POST'])
def index():
    '''
    root function that returns the root page
    '''

    title = 'Auto Blog'

    all_blogs = Blog.get_all_blogs()

    if all_blogs:
        blogs = all_blogs
        return render_template('index.html', title=title, all_blogs=blogs)
    elif not all_blogs:
        blog_message = 'No blogs available!'
        return render_template('index.html', title=title, blog_message=blog_message)


@main.route('/post', methods=['GET', 'POST'])
@login_required
def create_blog():
    blog_form = BlogForm()

    if blog_form.validate_on_submit():
        blog_title = blog_form.title.data
        blog = blog_form.blog_data.data
        url = blog_form.photo_url.data

        new_blog = Blog(title=blog_title, blog_content=blog, date_posted=datetime.now(), photo_url=url)
        new_blog.save_blog()

        send_blogs(new_blog)
        return redirect(url_for('main.blog', id=new_blog.id))

    return render_template('post.html', title='Create Blog', blog_form=blog_form)


@main.route('/blog/<int:id>', methods=['GET', 'POST'])
def blog(id):
    get_blog = Blog.query.get(id)
    get_blog_comments = Comment.get_blog_comments(id)

    if get_blog is None:
        abort(404)

    blog_format = markdown2.markdown(get_blog.blog_content, extras=["code-friendly", "fenced-code-blocks"])

    comment_form = CommentForm()

    if comment_form.validate_on_submit():
        user_name = comment_form.name.data
        user_email = comment_form.email.data
        user_comment = comment_form.comment_data.data

        new_comment = Comment(name=user_name, email=user_email, comment_content=user_comment,
                              date_comment=datetime.now(), blog_id=id)
        new_comment.save_comment()

        return redirect(url_for('main.blog', id=id))

    get_comments = Comment.get_blog_comments(id)

    return render_template('blog.html', blog_format=blog_format, get_blog=get_blog, title="Blog",
                           comment_form=comment_form, get_comments=get_comments, comments_count=len(get_blog_comments))


@main.route('/blog/<int:id>/update/pic', methods=['POST'])
@login_required
def update_pic(id):
    blog = Blog.get_single_blog(id)
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        blog.blog_pic = path
        # user_photo = PhotoProfile(pic_path = path,user = user)
        db.session.commit()
    return redirect(url_for('main.blog', id=id))

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
{{ simplemde.css}}
{{ simplemde.js }}
{% endblock %}

<!-----Navbar block------>
{% block navbar %}
{% include 'navbar.html' %}

{% endblock %}

<!-----Content block------>
{% block content %}
{% endblock %}

app/templates/blog.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container" id="blog-top">
    <div class="row">
        <div class="col-md-9 blog-header">
            <!-- Flash message -->
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            <h2> {{get_blog.title}} </h2>
            <p>{{get_blog.date_posted.strftime('%Y-%m-%d %H:%M')}} | {{comments_count}} comments</p>
            
        </div>
        <div class="col-md-12 image">
            <div class="col-md-7 blog-image">
                {% if get_blog.photo_url %}
                <img src="{{get_blog.photo_url}}" alt="">
                {% else %}
                <img src="{{url_for('static',filename='img/bg-blog.jpeg')}}" alt="blog-image">
                {% endif %}
                {% if current_user.is_authenticated %}
                <form action="{{url_for('main.update_pic',id=get_blog.id)}}" method="post" enctype="multipart/form-data">
                    <input type="file" name="photo" class="form-control" required>
                    <input class="submit" id="submit" type="submit">
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container comments">
        <div class="row">
            <div class="col-md-9 blog-content">
                {{blog_format|safe}}
            </div>
        </div>
        <hr><br>
        <div class="row blog-entries">
            <div class="col-md-9">
                <h3>Comments</h3>
                <hr>
                {% for comment in get_comments %}
                <div class="col-md-12">
                    <blockquote class="blockquote text-left">
                        <p class="mb-0"> {{comment.comment_content}} </p>
                        <footer class="blockquote-footer"> {{comment.name}} <cite title="Source Title">
                                {{comment.date_comment.strftime('%Y-%m-%d %H:%M')}} </cite></footer>
                        
                    </blockquote>
                </div>
                {% endfor %}
            </div>
            <hr>
            <div class="col-md-9">
                <form id="comments-form" class="form-group" method="POST">
                    {{comment_form.hidden_tag()}}

                    {{comment_form.comment_data}}
                    {% for error in comment_form.comment_data.errors%}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                    <br>
                    {{comment_form.name}}
                    {% for error in comment_form.name.errors%}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                    <br>
                    {{comment_form.email}}
                    {% for error in comment_form.email.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                    <br>
                    <p> {{comment_form.post}} </p>
                </form>
            </div>
        </div>
    </div>
</div>
<footer>
    <div class="container-fluid social text-center">
        <ul class="list-inline">
            <li class="list-inline-item">
                <a href="#">
                    <i class="fa fa-facebook fa-2x"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="#">
                    <i class="fa fa-twitter fa-2x"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="#">
                    <i class="fa fa-pinterest fa-2x"></i>
                </a>
            </li>
        </ul>
    </div>
</footer>
{% endblock %}

app/templates/forOwfor.html
{% extends 'base.html'%}

{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
<h1 class='fourOfour'>(500) Looks like something went wrong! <br> If the problem persists feel free
    to contact me. In the meantime, try refreshing.</h1>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block styles %}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/cstyle.css')}}">
{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css')}}">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Text+Me+One" rel="stylesheet">
<div class="container-fluid" id="top">
    <div class="row front-page">
        <div class="col-md-12">
            <!-- Flash message -->
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            <br>

            <h1 class='header'>Auto Blog</h1>
            <br>
            <br>
            <br>
            <div class="scroll">
                <a class="js-scroll-trigger" href="#blogs-content"><button class="btn btn-primary">Proceed</button></a>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid blogs">
    <div class="row blogs" id="blogs-content">
        <div class="col-md-12 blogs-title">
            <h1>{{blog_message}}</h1>
            <br>
            <br>
            <br>
            <h1 class = 'bloggs'>Blogs</h1>
            <hr width=50%>
            <br>
            <br>
        </div>
        {% for blog in all_blogs %}
        <div class="col-md-3 blogs-snippet" id = 'poster'>
            {% if blog.photo_url %}
            <a href="{{url_for('main.blog',id=blog.id)}}">
                <img src="{{blog.photo_url}}" alt="Loading Image" class="img-responsive">
            </a>
            {% else %}
            <a href="{{url_for('main.blog',id=blog.id)}}">
                <img src="{{url_for('static',filename='img/bg-blog.jpeg')}}" alt="blog-image" class="img-responsive">
            </a>
            {% endif %}
            <div class="blog-snippet-content">
                <h3><a href="{{url_for('main.blog',id=blog.id)}}">{{blog.title}}</a></h3>
                <hr>
                <p class="small"> Posted on: {{blog.date_posted.strftime('%Y-%m-%d %H:%M') }} </p>
                <p> {{blog.blog_content|truncate(300)}}<a href="{{url_for('main.blog',id=blog.id)}}">View More</a></p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

app/templates/macros.html
{% macro displayPitches(my_pitches) %}
{% for pitch in my_pitches %}
<div class="col-md-12 pitches">
    {% if pitch.user.profile_pic_path %}
    <p>
        <img src="{{url_for('static',filename = pitch.user.profile_pic_path)}}" alt="" class="img-thumbnail">
        <a href="/user/{{pitch.user.username}}&{{pitch.user.id}}">{{pitch.user.username|capitalize}}</a>
    </p>
    {% else %}
    <p>
        <img src="{{url_for('static',filename = 'photos/avatar.png')}}" alt="" class="img-thumbnail">
        <a href="/user/{{pitch.user.username}}&{{pitch.user.id}}">{{pitch.user.username|capitalize}}</a>
    </p>
    {% endif %}
    <p>{{pitch.pitch_content}}</p>
    <p class="small"> Category: {{pitch.pitch_category}} </p>
    <hr>
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="/pitch/{{pitch.id}}">Add Comment</a>
        </li>
    </ul>
</div>
{% endfor %}
{% endmacro %}

{% macro displayComments(my_comments) %}
{% for comment in my_comments %}
<hr>
<div class="comment">
    <p>
        {% if comment.user.profile_pic_path %}
            <img src="{{url_for('static',filename = comment.user.profile_pic_path)}}" alt="" class="img-thumbnail">
        {% else %}
            <img src="{{url_for('static',filename = 'photos/avatar.png')}}" alt="" class="img-thumbnail">
        {% endif %}
        <a href="/user/{{comment.user.username}}&{{comment.user.id}}">{{comment.user.username|capitalize}}</a>
    </p>
    <p>{{comment.comment_content}}</p>
</div>
{% endfor %}
{% endmacro %}

{% macro displayCategory(my_categories) %}
{% for category in my_categories %}
<div class="col-md-12 pitches">
    <p>
        <a href="/user/{{category.user.username}}&{{category.user.id}}">{{category.user.username|capitalize}}</a>
    </p>
    <p>{{category.pitch_content}}</p>
    <p class="small"> Category: {{category.pitch_category}} </p>
    <hr>
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="/pitch/{{category.id}}">Add Comment</a>
        </li>
    </ul>
</div>
{% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        {% if current_user.is_authenticated%}
        <a class="navbar-brand" href="{{url_for('main.create_blog')}}">Create blog</a>
        <a class="navbar-brand" href="{{url_for('auth.register')}}">Register</a>
        <a class="navbar-brand" href="{{url_for('auth.logout')}}">Sign out</a>
        {% else %}
        <a class="navbar-brand" href="{{url_for('auth.login')}}">Login in</a>
        {% endif %}
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> Auto Blog </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav nav-pills nav-justified">
                    <li class="dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">Blogs</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<br>
<br>

app/templates/post.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block styles %}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/cstyle.css')}}">
{% endblock %}

{% block content %}
<link href="https://fonts.googleapis.com/css?family=Text+Me+One" rel="stylesheet">
<div class="container" id="blog-top">
    <div class="row blog-entries">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <!-- Flash message -->
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            <div class="row blog-entries">
                <div class="col-md-12">
                    <h3 class = 'createblog'>Create Blog</h3>
                    <form action="" method="post">
                        {{blog_form.hidden_tag()}}
                        <p>{{blog_form.title.label}}</p>
                        <p>{{blog_form.title}}</p>
                        {% for error in blog_form.title.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}

                        <p>{{blog_form.photo_url.label}}</p>
                        <p>{{blog_form.photo_url}}</p>
                        {% for error in blog_form.photo_url.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}

                        <p>{{blog_form.blog_data.label}}</p>
                        <p>{{blog_form.blog_data}}</p>
                        {% for error in blog_form.blog_data.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}

                        <p>{{blog_form.post()}}</p>
                    </form>
                    {{simplemde.load}}
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

<footer>
    <div class="container-fluid social text-center one-pages">
        <ul class="list-inline">
            <li class="list-inline-item">
                <a href="#">
                    <i class="fa fa-facebook fa-2x"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="#">
                    <i class="fa fa-twitter fa-2x"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="#">
                    <i class="fa fa-pinterest fa-2x"></i>
                </a>
            </li>
        </ul>
    </div>
</footer>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
    <div class="card">
        <div class="row">
            <br>
            <br>
            <br>
            <div class="col-md-4 picture">
                <!-- Displaying profile photo -->
                {% if user.profile_pic_path %}
                <img src="{{url_for('static',filename = user.profile_pic_path)}}" alt="" class="img-thumbnail">
                {% else %}
                <img src="{{url_for('static',filename = 'photos/avatar.png')}}" alt="">
                {% endif %}
                <p class="user-tag"> {{user.username|capitalize}} </p>
                {% if user == current_user %}
                <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
                    <input type="file" name="photo" class="form-control" required>
                    <input type="submit" style="color:red">
                </form>
                {% endif %}
            </div>
            <div class="col-md-8 count">
                <!-- Displaying user bio -->
                <h3>Bio</h3>
                <hr>
                {% if user.bio %}
                <p> {{user.bio}} </p>
                {% else %}
                <p>{{user.username|capitalize}} has no bio</p>
                {% endif %}
                {% if user == current_user %}
                <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit Bio</a>
                <br>
                {% endif %}
                <br>
                <h3>Profile</h3>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope='col'></th>
                            <th scope='col'>Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="color:black;">
                            <td>Pitches</td>
                            <td>{{pitches_no|length}}</td>
                        </tr>
                        <tr>
                            <td>Comments</td>
                            <td>{{comments_no|length}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="card">
        <br>
        <br>
        <br>
        <div class="card-body update">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    {{wtf.quick_form(form)}}
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}